### ISSUE TITLE
Translation. Can this be translated?

### ISSUE THREAD

**Issue by dinism** [moodleou/moodle-qtype_pmatch#40] opened 2019-07-12 22:06 UTC
When creating a question:
![imagem](https://user-images.githubusercontent.com/14828021/61160961-9ed3bf80-a4f9-11e9-9bc2-2c9f4844b24c.png)
Thanks
I'm PT-PT translator

**Comment by germanvaleroelizondo** [comment] 2019-10-02 17:31
These English language strings are inside the edit_pmatch_form.php file.

If you edit them (e.g. with Notepad ++) locally you can get a working translation locally.

**Comment by timhunt** [comment] 2019-11-09 16:34
Duplicate of #46. Closing this one.

**Closed by timhunt** 2019-11-09 16:34 UTC
