### ISSUE TITLE
PHP 7.1+ issues with public const call

### ISSUE THREAD

**Issue by dustinbrisebois** [moodleou/moodle-qtype_pmatch#41] opened 2019-07-24 14:12 UTC
Greetings - 

PHP appears to have deprecated the use of public const calls within abstract class spaces

the calls here (and below)
https://github.com/moodleou/moodle-qtype_pmatch/blob/7c8f08af08194fa3377ceb9b487ce5b427f68beb/classes/local/spell/qtype_pmatch_spell_checker.php#L48

Cause a number of warnings as the scope appears unsupported beyond abstract classes.

**Comment by timhunt** [comment] 2019-08-22 15:32
Are you sure? I don't see any warnings caused by this.

**Comment by timhunt** [comment] 2019-11-09 16:32
Fixed in the latest version.

**Closed by timhunt** 2019-11-09 16:32 UTC
